'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'extension/index.html'),'utf8');
const panel=fs.readFileSync(path.join(root,'extension/js/panel.js'),'utf8');
const host=fs.readFileSync(path.join(root,'extension/jsx/host.jsx'),'utf8');
assert(!html.includes('secondTrack'));
assert(!html.includes('Ranh giữa hai dòng'));
assert(!html.includes('Căn bố cục bằng mẫu một dòng và hai dòng'));
assert(!panel.includes('secondTrack'));
assert(!panel.includes('calibrateWrap'));
assert(panel.includes("mode:'single-line'"));
assert(host.includes("version:'1.2.10'"));
assert(host.includes('plan.items.length!==1'));
assert(!host.includes('Track màu dòng 2'));
assert(panel.includes('C.timecode'));
assert(panel.includes("mode:'single-line'"));
assert(!panel.includes('secondTrack'));
assert(host.includes('return {ready:req.clips.length};'));
assert(!host.includes('partners:out'));
assert(html.includes('id="newVideo"'));
assert(panel.includes("rpc('forgetSession')"));
assert(host.includes('function forgetSession()'));
assert(host.includes('function forgetRecord(rec)'));
console.log('PASS panel/host expose only single-line workflow.');
